import { Router } from 'express';
import { auth, roles } from '../middlewares/auth.js';
import { wrap } from '../middlewares/error.js';
import { upload } from '../middlewares/upload.js';
import * as dashboard from '../controllers/dashboardController.js';
import * as cliente from '../controllers/clienteController.js';
import * as agenda from '../controllers/agendaController.js';
import * as financeiro from '../controllers/financeiroController.js';
import * as relatorio from '../controllers/relatorioController.js';
import * as promocao from '../controllers/promocaoController.js';
import BarbeiroController from '../controllers/barbeiroController.js';
const router = Router();
const barbeiro = new BarbeiroController();
router.use(auth, roles('ADMIN'));
router.get('/dashboard', wrap(dashboard.resumo));
router.get('/dashboard/carro-chefe', wrap(dashboard.carroChefe));
router.get('/dashboard/melhor-dia', wrap(dashboard.melhorDia));
router.get('/clientes', wrap(cliente.listar));
router.get('/clientes/:id', wrap(cliente.buscar));
router.get('/clientes-inativos', wrap(cliente.inativos));
router.get('/barbeiros', wrap(barbeiro.listarAdministrativo));
router.get('/agenda', wrap(agenda.agenda));
router.put('/agendamentos/:id', wrap(agenda.reschedule));
router.get('/financeiro', wrap(financeiro.resumo));
router.post('/pagamentos', wrap(financeiro.pagamento));
router.post('/despesas', wrap(financeiro.despesa));
router.get('/relatorios/:type', wrap(relatorio.listar));
router.post('/promocoes', wrap(promocao.cadastrar));
router.post('/imagens', upload.single('imagem'), (req, res) => {
    if (!req.file) return res.status(400).json({ erro: 'Envie JPG, PNG ou WebP de até 3 MB.' });
    res.status(201).json({ url: `/uploads/${req.file.filename}` });
});
export default router;
