import { Router } from 'express';
import authRoutes from './authRoute.js';
import servicoRoutes from './servicoRoute.js';
import barbeiroRoutes from './barbeiroRoute.js';
import agendamentoRoutes from './agendamentoRoute.js';
import adminRoutes from './adminRoute.js';
import { auth, roles } from '../middlewares/auth.js';
import { wrap } from '../middlewares/error.js';
import * as agendamento from '../controllers/agendamentoController.js';
import * as promocao from '../controllers/promocaoController.js';
import * as notificacao from '../controllers/notificacaoController.js';
import * as avaliacao from '../controllers/avaliacaoController.js';
import * as dashboard from '../controllers/dashboardController.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/servicos', servicoRoutes);
router.use('/barbeiros', barbeiroRoutes);
router.use('/agendamentos', agendamentoRoutes);
router.use('/admin', adminRoutes);
router.get('/horarios-disponiveis', wrap(agendamento.available));
router.get('/promocoes', wrap(promocao.listar));
router.get('/notificacoes', auth, wrap(notificacao.listar));
router.patch('/notificacoes/:id', auth, wrap(notificacao.marcarComoLida));
router.post('/avaliacoes', auth, roles('CLIENTE'), wrap(avaliacao.cadastrar));
router.get('/dashboard/faturamento-total', auth, roles('ADMIN'), wrap(dashboard.faturamentoTotal));
export default router;
